export enum FieldTypes {
  image = 'image',
  filter_country = 'filterCountry',
  filter_state = 'filterState',
  filter_city = 'filterCity',
  hidden = 'hidden',
  text = 'text',
  uploader = 'uploader',
  imageUploader = 'imageUploader',
  videoUploader = 'videoUploader',
  date = 'date',
  select = 'select',
  multiSelect = 'mutiSelect',
  checkbox = 'checkbox',
  filterCheckbox = 'filterCheckbox',
  filterMultiSelect = 'filterMultiSelect',
  filterCountry = 'filterCountry',
  filterState = 'filterState',
  filterCity = 'filterCity',
  city = 'city',
  video = 'video',
  hour = 'hour',
  none = 'none',
  label = 'label',
  tag = 'tag',
  dateLabel = 'dateLabel',
}

export type FieldTypesType = keyof typeof FieldTypes;
