export enum FieldTypes {
  boolean = "boolean",
  checkbox = "checkbox",
  city = "city",
  contentArea = "contentArea",
  date = "date",
  dateLabel = "dateLabel",
  filter_city = "filterCity",
  filter_country = "filterCountry",
  filter_state = "filterState",
  filterCheckbox = "filterCheckbox",
  filterCity = "filterCity",
  filterCountry = "filterCountry",
  filterMultiSelect = "filterMultiSelect",
  filterState = "filterState",
  hidden = "hidden",
  hour = "hour",
  image = "image",
  imageUploader = "imageUploader",
  label = "label",
  link = "link",
  multiSelect = "mutiSelect",
  none = "none",
  password = "password",
  select = "select",
  tag = "tag",
  text = "text",
  textarea = "textarea",
  uploader = "uploader",
  video = "video",
  videoUploader = "videoUploader",
}

export type FieldTypesType = keyof typeof FieldTypes;
